FROM node:22.16.0-slim

WORKDIR /home/folowin

COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.build.json ./
COPY tsconfig.json ./
COPY .env ./
COPY src ./src

RUN yarn install
RUN yarn global add @nestjs/cli
RUN yarn global add ts-node

EXPOSE 3001

CMD npm run migration:run && yarn run start:dev