import { MigrationInterface, QueryRunner } from "typeorm";

export class ExtendUserEntity1768253171442 implements MigrationInterface {
    name = 'ExtendUserEntity1768253171442'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "manager_customer_address" DROP CONSTRAINT "FK_a77ae2e4cdbcfefe64b7c44a627"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_ff0c0301a95e517153df97f6812"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_d5456fd7e4c4866fec8ada1fa10"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_43222947f71eee4febe010e3687"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_e60d0634847d803f8f9ade1059a"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_442eca5123705b2f8af27d5f065"`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP CONSTRAINT "FK_6e420052844edf3a5506d863ce6"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_904370c093ceea4369659a3c810"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_7e2fe82497aa29798b51511ada4"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_124456e637cca7a415897dce659"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_4af424d3e7b2c3cb26e075e20fc"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_89726ee65618314009b279e66e8"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_498abba8d72fb5bb8f9b58482ae"`);
        await queryRunner.query(`ALTER TABLE "manager_customer" DROP CONSTRAINT "FK_b94186685c7bc11c4bf53ba15c6"`);
        await queryRunner.query(`ALTER TABLE "manager_customer" DROP CONSTRAINT "FK_a57ac0e68f5e812eb6fe0152476"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a77ae2e4cdbcfefe64b7c44a62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3ef0cfb54934672d04f306479"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a8b1ee732fec84f0b8ed9b91a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_820d804c755d35961373ec1621"`);
        await queryRunner.query(`ALTER TABLE "manager_customer_address" RENAME COLUMN "managerCustomerId" TO "manager_customer_id"`);
        await queryRunner.query(`ALTER TABLE "product" RENAME COLUMN "categoryId" TO "category_id"`);
        await queryRunner.query(`ALTER TABLE "category" RENAME COLUMN "parentId" TO "parent_id"`);
        await queryRunner.query(`ALTER TABLE "product_variant" RENAME COLUMN "productId" TO "product_id"`);
        await queryRunner.query(`ALTER TABLE "customer" RENAME COLUMN "userId" TO "user_id"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "productVariantId"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "productVariantId"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "managerId"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "shippingMethodId"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "paymentMethodId"`);
        await queryRunner.query(`ALTER TABLE "manager_customer" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "manager_customer" DROP COLUMN "managerId"`);
        await queryRunner.query(`ALTER TABLE "media" ADD "product_id" uuid`);
        await queryRunner.query(`ALTER TABLE "media" ADD "product_variant_id" uuid`);
        await queryRunner.query(`ALTER TABLE "media" ADD "category_id" uuid`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "order_id" uuid`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "product_id" uuid`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "product_variant_id" uuid`);
        await queryRunner.query(`ALTER TABLE "order" ADD "customer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "order" ADD "manager_id" uuid`);
        await queryRunner.query(`ALTER TABLE "order" ADD "shipping_method_id" uuid`);
        await queryRunner.query(`ALTER TABLE "order" ADD "payment_method_id" uuid`);
        await queryRunner.query(`ALTER TABLE "manager_customer" ADD "customer_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "manager_customer" ADD "manager_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "is_blocked" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "user" ADD "last_login_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user" ADD "created_by" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD "blocked_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user" ADD "blocked_by" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD "blocked_reason" text`);
        await queryRunner.query(`ALTER TABLE "product" ALTER COLUMN "category_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "user_id" uuid`);
        await queryRunner.query(`CREATE INDEX "IDX_319c207dff8e77155354c4c1b7" ON "manager_customer_address" ("manager_customer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e867df11dc9e715a1fdc52d28c" ON "product_variant" ("product_id", "name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b4f91f27821e6523bab0be8d7f" ON "product_variant" ("product_id", "sku") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_60fd4ad86d1d112c417a4a123e" ON "manager_customer" ("manager_id", "customer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_is_blocked" ON "user" ("is_blocked") `);
        await queryRunner.query(`CREATE INDEX "idx_user_created_at" ON "user" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_user_roles" ON "user" ("roles") `);
        await queryRunner.query(`CREATE INDEX "idx_user_phone" ON "user" ("phone") `);
        await queryRunner.query(`CREATE INDEX "idx_user_email" ON "user" ("email") `);
        await queryRunner.query(`ALTER TABLE "manager_customer_address" ADD CONSTRAINT "FK_319c207dff8e77155354c4c1b7f" FOREIGN KEY ("manager_customer_id") REFERENCES "manager_customer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_1117b4fcb3cd4abb4383e1c2743" FOREIGN KEY ("parent_id") REFERENCES "category"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_1fe69e256dfd757e9e7651c6bf5" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_9e1d1cd45383b74e7cb9e692be9" FOREIGN KEY ("product_variant_id") REFERENCES "product_variant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_326851e1eda929d9a682fc62657" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD CONSTRAINT "FK_ca67dd080aac5ecf99609960cd2" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_e9674a6053adbaa1057848cddfa" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_5e17c017aa3f5164cb2da5b1c6b" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_19fe8036263238b4fb3866243bf" FOREIGN KEY ("product_variant_id") REFERENCES "product_variant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_cd7812c96209c5bdd48a6b858b0" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_e46a7f29f306dc88f2b77f5ae41" FOREIGN KEY ("manager_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_725d8733eda9a49f0bd19ab6174" FOREIGN KEY ("shipping_method_id") REFERENCES "shipping_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_451b11cb12bc07db00d19c5a511" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_5d1f609371a285123294fddcf3a" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "manager_customer" ADD CONSTRAINT "FK_428b2dbf761e1d171402ef8fd2f" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "manager_customer" ADD CONSTRAINT "FK_31706803761dd3a6b5bee7aaffa" FOREIGN KEY ("manager_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "manager_customer" DROP CONSTRAINT "FK_31706803761dd3a6b5bee7aaffa"`);
        await queryRunner.query(`ALTER TABLE "manager_customer" DROP CONSTRAINT "FK_428b2dbf761e1d171402ef8fd2f"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_5d1f609371a285123294fddcf3a"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_451b11cb12bc07db00d19c5a511"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_725d8733eda9a49f0bd19ab6174"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_e46a7f29f306dc88f2b77f5ae41"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_cd7812c96209c5bdd48a6b858b0"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_19fe8036263238b4fb3866243bf"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_5e17c017aa3f5164cb2da5b1c6b"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_e9674a6053adbaa1057848cddfa"`);
        await queryRunner.query(`ALTER TABLE "product_variant" DROP CONSTRAINT "FK_ca67dd080aac5ecf99609960cd2"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_326851e1eda929d9a682fc62657"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_9e1d1cd45383b74e7cb9e692be9"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_1fe69e256dfd757e9e7651c6bf5"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_1117b4fcb3cd4abb4383e1c2743"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1"`);
        await queryRunner.query(`ALTER TABLE "manager_customer_address" DROP CONSTRAINT "FK_319c207dff8e77155354c4c1b7f"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_is_blocked"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60fd4ad86d1d112c417a4a123e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4f91f27821e6523bab0be8d7f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e867df11dc9e715a1fdc52d28c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_319c207dff8e77155354c4c1b7"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "product" ALTER COLUMN "category_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "blocked_reason"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "blocked_by"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "blocked_at"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "last_login_at"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "is_blocked"`);
        await queryRunner.query(`ALTER TABLE "manager_customer" DROP COLUMN "manager_id"`);
        await queryRunner.query(`ALTER TABLE "manager_customer" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "payment_method_id"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "shipping_method_id"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "manager_id"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "product_variant_id"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "product_id"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "product_variant_id"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "product_id"`);
        await queryRunner.query(`ALTER TABLE "manager_customer" ADD "managerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "manager_customer" ADD "customerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ADD "paymentMethodId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ADD "shippingMethodId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ADD "managerId" uuid`);
        await queryRunner.query(`ALTER TABLE "order" ADD "customerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "productVariantId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "productId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "orderId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" ADD "categoryId" uuid`);
        await queryRunner.query(`ALTER TABLE "media" ADD "productVariantId" uuid`);
        await queryRunner.query(`ALTER TABLE "media" ADD "productId" uuid`);
        await queryRunner.query(`ALTER TABLE "customer" RENAME COLUMN "user_id" TO "userId"`);
        await queryRunner.query(`ALTER TABLE "product_variant" RENAME COLUMN "product_id" TO "productId"`);
        await queryRunner.query(`ALTER TABLE "category" RENAME COLUMN "parent_id" TO "parentId"`);
        await queryRunner.query(`ALTER TABLE "product" RENAME COLUMN "category_id" TO "categoryId"`);
        await queryRunner.query(`ALTER TABLE "manager_customer_address" RENAME COLUMN "manager_customer_id" TO "managerCustomerId"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_820d804c755d35961373ec1621" ON "manager_customer" ("customerId", "managerId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7a8b1ee732fec84f0b8ed9b91a" ON "product_variant" ("productId", "sku") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a3ef0cfb54934672d04f306479" ON "product_variant" ("name", "productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a77ae2e4cdbcfefe64b7c44a62" ON "manager_customer_address" ("managerCustomerId") `);
        await queryRunner.query(`ALTER TABLE "manager_customer" ADD CONSTRAINT "FK_a57ac0e68f5e812eb6fe0152476" FOREIGN KEY ("managerId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "manager_customer" ADD CONSTRAINT "FK_b94186685c7bc11c4bf53ba15c6" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_498abba8d72fb5bb8f9b58482ae" FOREIGN KEY ("managerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_89726ee65618314009b279e66e8" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_4af424d3e7b2c3cb26e075e20fc" FOREIGN KEY ("shippingMethodId") REFERENCES "shipping_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_124456e637cca7a415897dce659" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_7e2fe82497aa29798b51511ada4" FOREIGN KEY ("productVariantId") REFERENCES "product_variant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_904370c093ceea4369659a3c810" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variant" ADD CONSTRAINT "FK_6e420052844edf3a5506d863ce6" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_442eca5123705b2f8af27d5f065" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_e60d0634847d803f8f9ade1059a" FOREIGN KEY ("productVariantId") REFERENCES "product_variant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_43222947f71eee4febe010e3687" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_d5456fd7e4c4866fec8ada1fa10" FOREIGN KEY ("parentId") REFERENCES "category"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_ff0c0301a95e517153df97f6812" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "manager_customer_address" ADD CONSTRAINT "FK_a77ae2e4cdbcfefe64b7c44a627" FOREIGN KEY ("managerCustomerId") REFERENCES "manager_customer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
